### ISSUE TITLE
use modsecurity_rules_remote can set default rules where remote server is down

### ISSUE THREAD

**Issue by liuwenru** [SpiderLabs/ModSecurity-nginx#109]
use modsecurity_rules_remote can set default rules where remote server is down?

**Comment by victorhora** [comment]
Hi @liuwenru,

modsecurity_rules_remote assumes that a set of rules will be loaded. If it fails to download the rules for some reason, the default behaviour is that the web server (and ModSecurity) will not start.

If this is something that wouldn't work for you setup, we recommend setting the [SecRemoteRulesFailAction](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecRemoteRulesFailAction) where you can set the "Warn" flag so that the webserver continues to run.
In this scenario all your other rules would be loaded, regardless if they are the default basic [modsecurity.conf-recommended](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/modsecurity.conf-recommended) rules, CRS or your own custom rules.
