### ISSUE TITLE
Need help on Logging and Testing in Modsecurity-nginx + Libmodsecurity

### ISSUE THREAD

**Issue by vishaalgc** [SpiderLabs/ModSecurity-nginx#32]
Hi,

I have compiled libmodsecurity with ModSecurity-Nginx connector over Nginx-1.10.3 correctly without any issues. Now im looking at usage example given in wiki of the Modsecurity-nginx project. How do i add logging and do actual tests if the modsecurity is working or not in this setup ? Because im not seeing any difference in requests so far, so any info on how to add logs for this, May be an usage example would be great.

**Comment by defanator** [comment]
@vishaalgc ModSecurity connector module for nginx produces various messages related to rules processing directly to nginx' error log [1]. You may want to increase its level to `info`, simulate a number of  "bad" requests, and inspect error log for appeared entries.

[1] http://nginx.org/r/error_log

**Comment by redoracle** [comment]
I find out that the modsecurity-nginx connectors has some configuration differences respect to the standard version.
I had to add the crs rules directly in the "nginx server" directive (with "include <absolute path>", since in modsecurity.conf was not catching/loading them.

I can see in my modsecurity_debug.log rules are loaded now, but still no blocking yet.

This is what I did on my_server.conf under location /
modsecurity_rules '
                        SecRuleEngine On
                        SecDebugLog /etc/nginx/conf/modsec_debug.log
                        SecDebugLogLevel 9
                        include /etc/nginx/conf/modsec_includes.conf
                        ';

In modsec_includes.conf there is a list of rules to be included:
------
include /etc/nginx/conf/owasp-modsecurity-crs/crs-setup.conf
include /etc/nginx/conf/owasp-modsecurity-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
include /etc/nginx/conf/owasp-modsecurity-crs/rules/REQUEST-901-INITIALIZATION.conf
include ..etc..
-----
I also notice that the directive 
SecServerSignature is not working as well. (no error reported by the configuration test, but not doing anything)
SecAuditLogStorageDir is not creating/opening any files.

Are those issues normal? needs to be addressed? or I am doing something wrong?

**Comment by zimmerle** [comment]
Hi @redoracle,

The ***SecServerSignature*** is something that we are not willing to support as there is no generic way to implement it. It should not be a problem as the same level of functionality can be reached with the usage of other modules, such as: [ngx_http_headers_module](http://nginx.org/en/docs/http/ngx_http_headers_module.html)

***SecAuditLogStorageDir*** should be working fine. Did you manage to get it working? A good way to verify if it is really working is by enabling the DebugLogs. By doing that you should be able ito identify if a given request was relevant to be saved as an AuditLog.
