### ISSUE TITLE
Invalid input:  SecDisableBackendCompression On

### ISSUE THREAD

**Issue by ston3o** [SpiderLabs/ModSecurity-nginx#62]
SecDisableBackendCompression directive doesn't work with Libmodsecurity and ModSecurity-nginx.

Here my error : 

```
nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /etc/nginx/modsecurity.conf. Line: 209. Column: 32. Invalid input:  SecDisableBackendCompression On in /etc/nginx/nginx.conf:16
```

I can't read /var/log/modsec_audit.log file, output is encoding.

**Comment by victorhora** [comment]
Hi @ston3o 

The reason for the error message is because SecDisableBackendCompression is currently pending implementation for libModSecurity.

I have recently updated the reference manual to reflect that [SecDisableBackendCompression](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecDisableBackendCompression) is "To Be Implemented" (TBI).

**Comment by ston3o** [comment]
Hi @victorhora 

Ok, I have searched what "TBI" that mean and I did not found.
Anyway it's a good news !

Thank you :)

**Comment by victorhora** [comment]
Good point @ston3o. Maybe it's a good idea to add the meaning of TBI to the reference manual. :)

**Comment by zimmerle** [comment]
Hi,

I am closing this issue as this particular implementation may not be supported at libModSecurity. The reason for that is the fact that this specific configuration is too close to the webserver internals. There is no way to implement this functionality in a generic format inside the library, thus, leaving it to be controlled by the Web Server.

Notice that same functionality can be achieved by the utilization of ``gzip off`` on nginx: http://nginx.org/en/docs/http/ngx_http_gzip_module.html
